- name: Set the root password for all root accounts
  mysql_user: name=root host={{ item }} password='' priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != 'localhost'

- name: Configure mariadb for easy access as root user
  template: src=.my.cnf dest=~/.my.cnf owner=root group=root mode=0644

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=* state=absent

- name: Default User
  mysql_user: name={{ mariadb_admin_user }} host=% password={{ mariadb_admin_password }} priv=*.*:ALL,GRANT state=present

- name: remove the test database
  mysql_db: name=test state=absent
  notify:
    - Restart the mariadb service
