 - hosts: all
   roles:
    - { role: basics }
    - { role: updates }
    - { role: nginx }
    - { role: php }
    - { role: mysql }
    - { role: redis }
    - { role: nodejs }
    - { role: tests, when: testing_mode == 1 }
    - { role: symfony, when: projectname != 0 }
   post_tasks:
    - service: 
        name: nginx
        state: restarted
    - service:
        name: "php{{ php_version }}-fpm"
        state: restarted
